title: Developer-Nlog
description: "개발자 N의 생활"
author:
  name: "Nuruhee"
  email: "nuruhee@gmail.com"
  url: "https://https://dev-nuruhee.github.io/nlog/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "SomeHacker"
year : "2020"
